[package]
name = "quicklook"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "An easy to use Rust wrapper for Apple's QuickLookUI API."
keywords = ["macos", "appkit", "quicklook-ui", "apple"]
categories = ["os::macos-apis", "api-bindings"]
readme = "../README.md"

[package.metadata.docs.rs]
# Build for macOS so the objc2 dependencies can find the right symbols
default-target = "x86_64-apple-darwin"
# Pass the 'docsrs' flag so we can use it for conditional logic
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", features = ["NSEvent", "NSImage", "NSPanel"], default-features = false }
objc2-foundation = { version = "0.3.2", features = ["NSURL", "NSArray", "NSGeometry"], default-features = false }
objc2-quick-look-ui = "0.3.2"

[dev-dependencies]
objc2-app-kit = { version = "0.3.2", features = ["NSApplication"], default-features = false }
